---
# root_prefix: ""

postgres_version: 9.4
source_dir: "{{ '~/cnx/src' | expanduser }}"

# archive_db_name: cnxarchive
# archive_db_user: cnxarchive
# archive_db_password: cnxarchive
# archive_db_host: localhost
# archive_db_port: 5432

# memcached_hosts: localhost, foobar, goocar

# authoring_db_name: cnxauthoring
# authoring_db_user: cnxauthoring
# authoring_db_password: cnxauthoring
# authoring_db_host: localhost
# authoring_db_port: 5432

# archive_host: 0.0.0.0
# archive_port: 6789
# publishing_host: 0.0.0.0
# publishing_port: 6543
# authoring_host: 0.0.0.0
# authoring_port: 8080
