---
# Configure /etc/hosts file for development.

# Ansible requires python2, while Ubuntu >=15 strictly uses Python3.
- name: "install python-minimal (2.7) for ansible"
  hosts:
    - archive
    - publishing
    - authoring
    - frontend
    - worker
    - database
    - zope-plone
  become: yes
  # This is the critical line, otherwise Ansible will try
  # to run python to gather facts.
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: "sudo apt-get -y install python-minimal"

- name: "configure /etc/hosts file"
  hosts:
    - archive
    - publishing
    - authoring
    - frontend
    - worker
    - database
    - zope-plone
  tasks:
    - name: get dns from local /etc/hosts
      local_action: "command grep -E '^${% for group in groups.all %}|{{ '\\<%s\\>'|format(group) }}{% endfor %}' /etc/hosts"
      register: etc_hosts
    - name: remove old entries from target /etc/hosts
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        regexp: "{{ item }}"
        state: absent
      with_items: "{{ groups.all }}"
    - name: add new entries to target /etc/hosts
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        line: "{{ item }}"
        insertbefore: BOF
      with_items: "{{ etc_hosts.stdout_lines }}"
