---
# Used to deployment cnx-archive to existing
# (manually created) legacy-staging#.cnx.org boxes.

# An instance of cnx-buildout (a zope site) has already been setup on these
# machines. As such, postgresql has also been installed. This playbook has
# been created to install cnx-archive on those machines.
#
# Note, just installing cnx-archive on these machines isn't enough.
# The database schema that was used to create these instances is from
# Products.RhaptosModuleStorage, which contains an older version
# of the schema; so you'll need to manually upgrade some of the parts. =/

# Note, 'local' (the host name in the inventory)
#   should be assigned ``ansible_connection=local``.

- name: create /var/www, if it does not exist
  hosts: archive
  vars:
    user: "www-data"
    user_home: "/var/www"
  tasks:
    - name: create www-data home
      become: yes
      file:
        path: "{{ user_home }}"
        state: directory
        owner: www-data
        group: www-data

# +++
# Source gathering
# +++

- name: package up source for shipment
  hosts: local
  tasks:
    - include: tasks/checkout.yml
    - include: tasks/archive_source.yml

- name: send source to hosts
  hosts:
    - archive
    - database
  tasks:
    - include: tasks/plant_source.yml

# +++
# Applications
# +++

- name: install postgres extensions
  hosts:
    - database
  tasks:
    - include: tasks/install_plxslt.yml
    - include: tasks/install_session_exec.yml

- name: install supervisor
  hosts:
    - archive
  tasks:
    - include: tasks/install_supervisor.yml
      
- name: install archive
  hosts: archive
  tasks:
    - include: tasks/install_archive.yml
