---
# Builds the cnx plone site.

- name: "notify #cnx-stream of the deployment (start)"
  hosts:
    - zope-plone
  vars:
    msg: "Started deploy to {{ inventory_hostname }} :hourglass_flowing_sand:"
    channel: "#cnx-stream"
  tasks:
    - include: tasks/notify_slack.yml

- name: copy deploy key
  hosts: zope-plone
  vars:
    user: "www-data"
    user_home: "/var/www"
  tasks:
    - name: create www-data home
      become: yes
      file:
        path: "{{ user_home }}"
        state: directory
        owner: www-data
        group: www-data
    - include: tasks/copy_deploy_key.yml

- name: test git over ssh using the www-data user
  hosts: zope-plone
  become: yes
  become_user: www-data
  tasks:
    - shell: "ssh -T git@github.com"
      register: git_test
      failed_when: "{% if git_test.rc != 1 and 'Hi cnx-devops! You\\'ve successfully authenticated' not in git_test.stderr %} True {% else %} False {% endif %}"

- name: install cnxml dtd pkgs
  hosts: zope-plone
  tasks:
    - include: tasks/install_cnxml_dtd.yml

- name: build python 2.4
  hosts: zope-plone
  tasks:
    - stat: path=/usr/local/bin/python2.4
      register: python24_binary
    - include: tasks/install_python24.yml
      when: not python24_binary.stat.exists

- name: install postgres database
  hosts: zope-plone
  tasks:
    - include: tasks/install_postgres.yml
  roles:
    - multimac.launchd

- name: checkout cnx-buildout
  hosts: local
  vars:
    source:
      - name: cnx-buildout
        repo: git@github.com:Rhaptos/cnx-buildout.git
        default_version: HEAD
  tasks:
    - include: tasks/checkout.yml
    - include: tasks/archive_source.yml

- name: send source to hosts
  hosts: zope-plone
  vars:
    source:
      - name: cnx-buildout
        repo: git@github.com:Rhaptos/cnx-buildout.git
        default_version: HEAD
  tasks:
    - include: tasks/plant_source.yml

- name: install cnx plone site
  hosts: zope-plone
  tasks:
    - include: tasks/install_cnx_buildout.yml
    - include: tasks/create_rhaptos_site.yml

- name: "notify #cnx-stream of the deployment (end)"
  hosts:
    - zope-plone
  vars:
    msg: "Deploy to {{ inventory_hostname }} was successful :heavy_check_mark:"
    channel: "#cnx-stream"
  tasks:
    - include: tasks/notify_slack.yml
