---
# This forcibly wipes and loads data from files/cnxarchive_dump.tar.gz.

- name: get database details
  hosts: database
  vars_prompt:
    - name: "db_name"
      prompt: "What database are we pushing to?"
      default: cnxarchive
    - name: "db_user"
      prompt: "What database user should we use?"
      default: postgres
    - name: "db_password"
      prompt: "What password should we use for the database user?"
  tasks:
    - set_fact:
        db_name: "{{ db_name }}"
        db_user: "{{ db_user }}"
        db_password: "{{ db_password }}"

- name: transfer database dump
  hosts: database
  tasks:
    - name: create directory for database dump
      file:
        path: /tmp/cnxarchive_dump
        state: directory
    - unarchive:
        src: "cnxarchive_dump.tar"
        dest: "/tmp/cnxarchive_dump"

- name: forcibly push data
  hosts: database
  tasks:
    - include: tasks/create_db_user.yml
    - name: drop database
      become: yes
      become_user: postgres
      shell: "dropdb {{ db_name }}"
      ignore_errors: yes
    - name: create database
      become: yes
      become_user: postgres
      shell: "createdb -O {{ db_user }} {{ db_name }}"
    - name: load database without files
      shell: "zcat /tmp/cnxarchive_dump/cnxarchive_dump_without_files.sql.gz | psql -U {{ db_user }} {{ db_name }} -f -"

    - name: load files table
      shell: zcat '/tmp/cnxarchive_dump/cnxarchive_index_files.txt.gz' '/tmp/cnxarchive_dump/cnxarchive_other_files.txt.gz' | psql -U {{ db_user }} {{ db_name }} -c "ALTER TABLE files DISABLE TRIGGER ALL; COPY files (fileid, md5, sha1, file, media_type) FROM STDIN; ALTER TABLE files ENABLE TRIGGER ALL;"

    - name: load module files table
      shell: zcat '/tmp/cnxarchive_dump/cnxarchive_index_module_files.txt' | psql -U {{ db_user }} {{ db_name }} -c "ALTER TABLE module_files DISABLE TRIGGER ALL; COPY module_files (module_ident, fileid, filename) FROM STDIN; ALTER TABLE module_files ENABLE TRIGGER ALL;"
    - name: remove dump files
      file:
        path: /tmp/cnxarchive_dump
        state: absent
