---
# Build webview... This is separate from the install, because it happens on
# the local host and the source is then transfered to the target
# by another task.

# +++
# Prerequisites
# +++

# FIXME Debian nodejs package is too old

- name: download nodejs (on Debian)
  when: ansible_os_family == "Debian"
  unarchive:
    src: https://nodejs.org/dist/v4.2.4/node-v4.2.4-linux-x64.tar.gz
    dest: /tmp/
    copy: no

- register: modified_path
  shell: echo "{{ ansible_os_family == 'Darwin' and ansible_env.PATH or '/tmp/node-v4.2.4-linux-x64/bin:' + ansible_env.PATH }}"

- name: install nodejs and npm packages (on Darwin)
  when: ansible_os_family == "Darwin"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: install js build tool
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - bower
    - grunt-cli
  environment:
    PATH: "{{ modified_path.stdout }}"

- name: nodejs version
  command: node --version
  environment:
    PATH: "{{ modified_path.stdout }}"
  register: nodejs_version

- debug:
    msg: "Using nodejs version {{ nodejs_version.stdout }}"

- name: npm version
  command: npm --version
  environment:
    PATH: "{{ modified_path.stdout }}"
  register: npm_version

- debug:
    msg: "Using npm version {{ npm_version.stdout }}"

# +++
# Build
# +++

- name: is this a new build?
  stat: path="{{ source_dir }}/webivew/node_modules"
  register: modules_dir

# FIXME conditionally run this
- name: install webview
  when: not modules_dir.stat.exists
  npm:
    path: "{{ source_dir }}/webview"
    global: no
  environment:
    PATH: "{{ modified_path.stdout }}"

# FIXME npm >= 3.x changed it's behavior for peer dependencies
#       the webview readme needs updated to reflect this cryptic issue.
#       https://docs.npmjs.com/files/package.json#peerdependencies
- name: install coffeelint
  npm:
    path: "{{ source_dir }}/webview"
    name: coffeelint@^1
    global: no
    state: present
  environment:
    PATH: "{{ modified_path.stdout }}"

- name: update webview
  when: modules_dir.stat.exists
  command: npm run-script upgrade
  args:
    chdir: "{{ source_dir }}/webview"
  environment:
    PATH: "{{ modified_path.stdout }}"

- name: build webview dist
  command: npm run-script dist
  args:
    chdir: "{{ source_dir }}/webview"
  environment:
    PATH: "{{ modified_path.stdout }}"

- name: remove nodejs source code (on Debian)
  when: ansible_os_family == "Debian"
  file:
    path: /tmp/node-v4.2.4-linux-x64
    state: absent
