---
# Build webview... This is separate from the install, because it happens on
# the local host and the source is then transfered to the target
# by another task.

# +++
# Prerequisites
# +++

# FIXME NOT IMPLEMENTED o Debian

# - name: install nodejs and npm packages (on Debian)
#   when: ansible_os_family == "Debian"
#   become: yes
#   apt:
#     name: "{{ item }}"
#     state: present
#   with_items:
#      - nodejs-dev
#      - nodejs-legacy
#      - npm

- name: install nodejs and npm packages (on Darwin)
  when: ansible_os_family == "Darwin"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: install js build tool
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - bower
    - grunt-cli

# +++
# Build
# +++

- name: is this a new build?
  stat: path="{{ source_dir }}/webivew/node_modules"
  register: modules_dir

# FIXME conditionally run this
- name: install webview
  when: not modules_dir.stat.exists
  npm:
    path: "{{ source_dir }}/webview"
    global: no

# FIXME npm >= 3.x changed it's behavior for peer dependencies
#       the webview readme needs updated to reflect this cryptic issue.
#       https://docs.npmjs.com/files/package.json#peerdependencies
- name: install coffeelint
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  npm:
    path: "{{ source_dir }}/webview"
    name: coffeelint@^1
    global: no
    state: present

- name: update webview
  when: modules_dir.stat.exists
  command: npm run-script upgrade
  args:
    chdir: "{{ source_dir }}/webview"

- name: build webview dist
  command: npm run-script dist
  args:
    chdir: "{{ source_dir }}/webview"
