---
# Configure PDF Generation

# TODO Create supervisor configuration

- name: install dependencies
  when: ansible_distribution_release != 'trusty'
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - python-imaging
    - gif2png
    - cjk-latex
    - texlive-latex-extra
    - xsltproc
    - xvfb
    - xfonts-base
    - libreoffice
    - imagemagick
    - tralics
    - unzip
    - libxml2-utils
    - texlive-latex3
    - libedit-dev
    - zip
    - libreoffice-script-provider-python
    - ruby
    - inkscape
    - docbook-xsl-ns
    - texlive-fonts-recommended
    - memcached
    - librsvg2-bin
    - otf-stix
    - openjdk-8-jdk

- name: install princexml (trusty)
  when: ansible_distribution_release == "trusty"
  apt:
    deb: "http://www.princexml.com/download/prince_10r7-1_ubuntu14.04_amd64.deb"
  become: yes

- name: install princexml
  when: ansible_distribution_release != "trusty"
  apt:
    deb: "http://www.princexml.com/download/prince_10r7-1_ubuntu16.04_amd64.deb"
  become: yes

- name: create directory for urw fonts
  become: yes
  file:
    path: "/usr/share/fonts/urw"
    state: directory
    mode: 0755

- name: download urw fonts
  become: yes
  get_url:
    url: "http://svn.ghostscript.com/ghostscript/trunk/ghostpdl/urwfonts/{{ item }}"
    dest: "/usr/share/fonts/urw"
  with_items:
    - URWPalladioL-Bold.ttf
    - URWPalladioL-BoldItal.ttf
    - URWPalladioL-Ital.ttf
    - URWPalladioL-Roma.ttf
