---

- name: make sure ~/.ssh exists
  become: yes
  become_user: "{{ user }}"
  file:
    state: directory
    path: "{{ user_home }}/.ssh"
    mode: 0700

- name: copy deploy key
  when: deploy_key is defined
  become: yes
  copy:
    content: "{{ deploy_key }}"
    dest: "{{ user_home }}/.ssh/cnx-devops_rsa"
    mode: 0600
    owner: "{{ user }}"

- name: make sure ~/.ssh/config exists
  when: deploy_key is defined
  become: yes
  become_user: "{{ user }}"
  file:
    state: touch
    path: "{{ user_home }}/.ssh/config"
    mode: 0600

- name: configure ssh to use deploy key for github
  when: deploy_key is defined
  become: yes
  become_user: "{{ user }}"
  blockinfile:
    dest: "{{ user_home }}/.ssh/config"
    content: |
      HostName github.com
      IdentityFile ~/.ssh/cnx-devops_rsa
    validate: grep 'ANSIBLE MANAGED BLOCK' %s

- name: ensure github.com is a known host
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    dest: "{{ user_home }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
