---
# Create a postgresql database user with superuser privileges.

# Installed for the postgresql_* ansible modules.
- become: yes
  apt:
    name: python-psycopg2
    state: present

- name: create the db user
  postgresql_user:
    db: postgres
    login_user: postgres
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    # FIXME There is no reason to make this user a SUPERUSER
    role_attr_flags: SUPERUSER
