---
# Creates a self-signed certificate.
# The certificate key is signed with ``cert_password``,
# this property is required for the creation of the certificate.
# However, the resulting certificate key file will be unencrypted for convenience.

# Properties:
#  - cert_password: used when creating the certificate signing key
#  - cert_domain: a string for the domain (e.g. example.com)
#  - cert_crt_filepath: where to put the created crt file
#  - cert_key_filepath: where to put the created signing key file

- file:
    path: tmp
    state: directory

- name: generate a private key
  expect:
    command: "openssl genrsa -des3 -out server.key 1024"
    chdir: tmp
    responses:
      "Enter pass phrase for server.key:": "{{ cert_password }}"

- name: generate a csr
  expect:
    command: "openssl req -new -key server.key -out server.csr"
    chdir: tmp
    responses:
      "Enter pass phrase for server.key:": "{{ cert_password }}"        
      "Country Name \\(2 letter code\\) \\[AU\\]\\:": "US"
      "State or Province Name \\(full name\\) \\[Some-State\\]\\:": "TX" 
      "Locality Name \\(eg, city\\) \\[\\]:": "Houston"
      "Organization Name \\(eg, company\\) \\[Internet Widgits Pty Ltd\\]\\:": "OpenStax"
      "Organizational Unit Name \\(eg, section\\) \\[\\]\\:": ""
      "Common Name \\(e.g. server FQDN or YOUR name\\) \\[\\]\\:": "{{ cert_domain }}"
      "Email Address \\[\\]\\:": ""
      "A challenge password \\[\\]\\:": ""
      "An optional company name \\[\\]\\:": ""

- copy:
    src: tmp/server.key
    dest: tmp/server.key.orig

- name: remove passphrase from key
  expect:
    command: "openssl rsa -in server.key.orig -out server.key"
    chdir: tmp
    responses:
      "Enter pass phrase for server.key.orig:": "{{ cert_password }}"        

- name: generate a self-signed certificate
  command: "openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt"
  args:
    chdir: tmp

- name: move crt to final location
  copy:
    src: tmp/server.crt
    dest: "{{ cert_crt_filepath }}"

- name: move key to final location
  copy:
    src: tmp/server.key
    dest: "{{ cert_key_filepath }}"
