---
# Create a postgresql database.

# Installed for the postgresql_* ansible modules.
- become: yes
  apt:
    name: python-psycopg2
    state: present

- name: create the archive db
  postgresql_db:
    login_user: postgres
    name: "{{ db_name }}"
    encoding: "utf-8"
    # FIXME The owner should not be the same as the user.
    owner: "{{ db_owner }}"
    state: present
