---
# Installs webview with all the dependencies.

# +++
# Install
# +++

- name: copy dist build to source
  copy:
    src: "{{ local_source_dir }}/webview/dist"
    dest: "{{ source_dir }}/webview"

# +++
# Configure
# +++

- name: configure webview settings.js
  template:
    src: var/www/cnx/scripts/settings.js
    dest: "{{ source_dir }}/webview/dist/scripts/settings.js"

- name: configure the webview nginx site
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  template:
    src: etc/nginx/sites-available/webview
    dest: "{{ root_prefix }}/etc/nginx/sites-available/webview"

- name: enable the webview nginx site
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  file:
    src: "{{ root_prefix }}/etc/nginx/sites-available/webview"
    dest: "{{ root_prefix }}/etc/nginx/sites-enabled/webview"
    state: link

# +++
# Deploy
# +++

# TODO We need to copy the built files to a staging location,
#      make the config changes,
#      then use a symlink to designate the active build.
- name: link dist to var/www
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  file:
    src: "{{ source_dir }}/webview/dist"
    # FIXME This is copying to .../www/cnx/dist, which isn't correct
    dest: "{{ root_prefix }}/var/www/webview"
    state: link

# +++
# Init service
# +++

- name: restart nginx (on Darwin)
  when: ansible_os_family == "Darwin"
  become: yes
  launchd:
    domain: "system"
    label: "homebrew.mxcl.nginx"
    state: restarted

- name: reload nginx (on Debian)
  when: ansible_os_family == "Debian"
  become: yes
  service:
    name: nginx
    state: reloaded
