---
# Installs webview with all the dependencies.

# +++
# Prerequisites
# +++

- name: install nodejs and npm packages (on Debian)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
     - nodejs-dev
     - nodejs-legacy
     - npm

- name: install nodejs and npm packages (on Darwin)
  when: ansible_os_family == "Darwin"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: install js build tool
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - bower
    - grunt-cli

# +++
# Install
# +++

- name: is this a new build?
  stat: path="{{ source_dir }}/webivew/node_modules"
  register: modules_dir

# FIXME conditionally run this
- name: install webview
  when: not modules_dir.stat.exists
  npm:
    path: "{{ source_dir }}/webview"
    global: no

# FIXME npm >= 3.x changed it's behavior for peer dependencies
#       the webview readme needs updated to reflect this cryptic issue.
#       https://docs.npmjs.com/files/package.json#peerdependencies
- name: install coffeelint
  npm:
    path: "{{ source_dir }}/webview"
    name: coffeelint@^1
    global: no
    state: present

- name: update webview
  when: modules_dir.stat.exists
  command: npm run-script upgrade
  args:
    chdir: "{{ source_dir }}/webview"

# +++
# Configure
# +++

- name: configure the cnx frontend nginx site
  template:
    src: etc/nginx/sites-available/cnx
    dest: /usr/local/etc/nginx/sites-available/cnx

- name: enable the nginx site
  file:
    src: /usr/local/etc/nginx/sites-available/cnx
    dest: /usr/local/etc/nginx/sites-enabled/cnx
    state: link

# +++
# Compile
# +++

- name: build webview dist
  command: npm run-script dist
  args:
    chdir: "{{ source_dir }}/webview"

# TODO Move dist to accessible location

# +++
# Init service
# +++

- name: restart the nginx (on Darwin)
  when: ansible_os_family == "Darwin"
  launchd:
    domain: "gui/{{ ansible_user_uid }}"
    label: "homebrew.mxcl.nginx"
    state: restarted
