---

# +++
# Install
# +++

- name: install nginx (on Debian)
  when: ansible_os_family == 'Debian'
  become: yes
  apt:
    name: nginx
    state: present

- name: install nginx (on Darwin)
  when: ansible_os_family == 'Darwin'
  homebrew:
    name: nginx
    state: present

# +++
# Configure
# +++

- name: disable default site
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  file:
    path: "{{ root_prefix }}/etc/nginx/sites-enabled/default"
    state: absent

# FIXME This puts a toy (but functional) config in place
- name: install nginx.conf (on Darwin)
  when: ansible_os_family == "Darwin"
  copy:
    src: "etc/nginx/nginx.conf"
    dest: "{{ root_prefix }}/etc/nginx/nginx.conf"
    mode: 0644

- name: ensure nginx/sites-{available,enabled} & nginx/conf.d (on Darwin)
  when: ansible_os_family == "Darwin"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /usr/local/etc/nginx/sites-available
    - /usr/local/etc/nginx/sites-enabled
    - /usr/local/etc/nginx/conf.d

# +++
# Init serivce
# +++
# (On Darwin) We use a custom plist file here so that we won't have
# nginx start on system startup.
# (On Darwin) nginx is setup to run under root privileges so that it
# can use port 443.

- name: copy plist to launchd directory (on Darwin)
  when: ansible_os_family == "Darwin"
  become: yes
  copy:
    src: "osx/Library/LaunchAgents/homebrew.mxcl.nginx.plist"
    dest: "/Library/LaunchAgents/homebrew.mxcl.nginx.plist"
    mode: 0600

# Note, this will not work within 'tmux' or 'screen'. launchctl results in ``Operation not permitted``
# If you run into this issue, see https://apple.stackexchange.com/questions/41412/using-tmux-and-pbpaste-pbcopy-and-launchctl
- name: load the nginx launchd config (on Darwin)
  when: ansible_os_family == "Darwin"
  become: yes
  launchd:
    domain: "system"
    path: "/Library/LaunchAgents/homebrew.mxcl.nginx.plist"
    state: loaded
# If you ever need to remove this use: ``sudo launchctl bootout system /Library/LaunchAgents/homebrew.mxcl.nginx.plist``

# FIXME Doing some/all of this as a role would allow for better restarting of the service.
- name: restart nginx (on Darwin)
  when: ansible_os_family == "Darwin"
  become: yes
  launchd:
    domain: "system"
    label: "homebrew.mxcl.nginx"
    state: restarted

- name: start nginx (on Debian)
  when: ansible_os_family == "Debian"
  become: yes
  service:
    name: nginx
    state: started
