---
# Installs and configures Memcached.

# +++
# Install
# +++

- name: install memcached
  become: yes
  apt:
    name: memcached
    state: present

# +++
# Init service
# +++

- name: start memcached
  become: yes
  service:
    name: memcached
    state: started
