---
# Installs archive and publishing with all the dependencies.
#
# The virtualenvs are installed to /usr/local/var/cnx/venvs
# and the configuration is installed to /usr/local/etc/cnx/.

# +++
# Prerequisites
# +++

- include_vars: "{{ inventory_dir }}/vars/secrets.yml"

# FIXME (On Darwin) Missing prerequisites for libxml2 and libxslt.

# TODO Kill this dependency by prebuilding or using packaged versions
#      of the application/library.
- name: install build utilities
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libxml2-dev
    - libxslt-dev
    # pkg-config is required for plxslt builds
    - pkg-config
    - python-dev

# Installed for the postgresql_* ansible modules.
- when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: python-psycopg2
    state: present

- when: ansible_os_family == "Darwin"
  pip:
    name: psycopg2
    state: present

- name: install virtualenv (on Debian)
  # BBB (1-Feb-2016) ubuntu 14.04
  ##when: ansible_os_family == "Debian"
  when: ansible_os_family == "Debian" and ansible_distribution_release != "trusty"
  become: yes
  apt:
    name: virtualenv
    state: present

# BBB (1-Feb-2016) unbuntu 14.04
- name: install virtualenv (on Ubuntu 14.04)
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"
  become: yes
  apt:
    name: python-virtualenv
    state: present

# +++
# Install virtualenv(s)
# +++

- stat:
    path: "{{ root_prefix }}/var/cnx/venvs"
  register: venvs_dir

- name: ensure the venvs directory exists
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  when: not venvs_dir.stat.exists
  file:
    path: "{{ root_prefix }}/var/cnx/venvs"
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"

- name: create the archive virtualenv
  pip:
    name: pip
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/archive"
    virtualenv_python: python2

- name: create the publishing virtualenv
  pip:
    name: pip
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/publishing"
    virtualenv_python: python2

# +++
# Install
# +++

- name: install plxslt
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  shell: "make PG_CONFIG={{ ansible_os_family == 'Darwin' and '/usr/local/opt/postgresql-{}/bin/pg_config'.format(postgres_version) or 'pg_config' }} && make PG_CONFIG={{ ansible_os_family == 'Darwin' and '/usr/local/opt/postgresql-{}/bin/pg_config'.format(postgres_version) or 'pg_config' }} install"
  args:
    chdir: "{{ source_dir }}/plxslt"

- name: install session_exec
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  shell: "make USE_PGXS=1 PG_CONFIG={{ ansible_os_family == 'Darwin' and '/usr/local/opt/postgresql-{}/bin/pg_config'.format(postgres_version) or 'pg_config' }} && make USE_PGXS=1 PG_CONFIG={{ ansible_os_family == 'Darwin' and '/usr/local/opt/postgresql-{}/bin/pg_config'.format(postgres_version) or 'pg_config' }} install"
  args:
    chdir: "{{ source_dir }}/session_exec"

# ---
- name: restart the postgres (on Darwin)
  when: ansible_os_family == "Darwin"
  launchd:
    domain: "gui/{{ ansible_user_uid }}"
    label: "homebrew.mxcl.postgresql-{{ postgres_version }}"
    state: restarted
# ---

- name: install archive packages
  pip:
    name: "{{ item }}"
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/archive"
    state: present
  with_items:
    - pyramid_sawing

- name: install (local) archive packages
  pip:
    name: "{{ source_dir }}/{{ item }}"
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/archive"
    state: present
  with_items:
    - cnx-query-grammar
    - rhaptos.cnxmlutils
    - cnx-epub
    - plpydbapi
    - cnx-archive

- name: install publishing packages
  pip:
    name: "{{ item }}"
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/publishing"
    state: present
  with_items:
    - pyramid_sawing

- name: install (local) publishing packages
  pip:
    name: "{{ source_dir }}/{{ item }}"
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/publishing"
    state: present
  with_items:
    - cnx-query-grammar
    - rhaptos.cnxmlutils
    - cnx-epub
    - plpydbapi
    - cnx-archive
    - openstax-accounts
    - cnx-publishing

# +++
# Configure
# +++

- name: ensure the etc directories exists
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  file:
    path: "{{ root_prefix }}/etc/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - cnx
    - cnx/archive
    - cnx/publishing

- name: render configuration
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0700
    owner: "{{ ansible_user_id }}"
  with_items:
    - {src: "etc/cnx/archive/app.ini",
       dest: "{{ root_prefix }}/etc/cnx/archive/app.ini"}
    - {src: "etc/cnx/publishing/app.ini",
       dest: "{{ root_prefix }}/etc/cnx/publishing/app.ini"}

# TODO make logging configuration files for pyramid_sawing

# +++
# Init databases
# +++

- name: create the archive db user
  postgresql_user:
    db: postgres
    login_user: "{{ ansible_os_family == 'Darwin' and ansible_user_id or 'postgres' }}"
    login_unix_socket: "{{ ansible_os_family == 'Darwin' and '/tmp' or '' }}"
    name: "{{ archive_db_user }}"
    password: "{{ archive_db_password }}"
    # FIXME There is no reason to make this user a SUPERUSER
    role_attr_flags: SUPERUSER

- name: create the archive db
  postgresql_db:
    login_user: "{{ ansible_os_family == 'Darwin' and ansible_user_id or 'postgres' }}"
    login_unix_socket: "{{ ansible_os_family == 'Darwin' and '/tmp' or '' }}"
    name: "{{ archive_db_name }}"
    encoding: "utf-8"
    # FIXME The owner should not be the same as the user.
    owner: "{{ archive_db_user }}"
    state: present

# Note, the setup current **assumes** that the publishing and archive database
# is the same database. There has been no reason to split these yet, so we won't.

# FIXME These initialize tasks run to failures. Ideally, it's be nice if
#       they gracefully bailed out with a meaningful message.

- name: initialize archive db
  command: "{{ root_prefix }}/var/cnx/venvs/archive/bin/cnx-archive-initdb {{ root_prefix }}/etc/cnx/archive/app.ini"
  register: archive_initdb_cmd
  failed_when: "archive_initdb_cmd.rc > 0 and 'Database is already initialized' not in archive_initdb_cmd.stderr"

- name: initialize publishing db
  when: "'Database is already initialized' not in archive_initdb_cmd.stderr"
  command: "{{ root_prefix }}/var/cnx/venvs/publishing/bin/cnx-publishing-initdb {{ root_prefix }}/etc/cnx/publishing/app.ini"

# +++
# Init service
# +++

- name: configure archive under supervisor
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  template:
    src: etc/supervisor/conf.d/archive.conf
    dest: "{{ root_prefix }}/etc/supervisor/conf.d/archive.conf"
    mode: 0644
  register: supervisor_archive_conf

- name: configure publishing under supervisor
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  template:
    src: etc/supervisor/conf.d/publishing.conf
    dest: "{{ root_prefix }}/etc/supervisor/conf.d/publishing.conf"
    mode: 0644
  register: supervisor_publishing_conf

# Unforntuately supervisor's init script doesn't support reload,
# but supervisorctl does... so maybe there is a way to reload?
- name: restart supervisor
  when: ansible_os_family == "Debian"
  become: yes
  service:
    name: supervisor
    state: "{{ (supervisor_archive_conf.changed or supervisor_publishing_conf.changed) and 'restarted' or 'started' }}"
