---
# Installs cnx zope instance with all the dependencies.

# +++
# Prerequisites
# +++

- name: install dependencies
  when: ansible_distribution_release == 'trusty'
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - openjdk-7-jre-headless
    - libjpeg-dev
    - libpng-dev
    - build-essential
    # lxml dependencies
    - libxml2-dev
    - libxslt1-dev
    # required by mr.developer
    - git
- name: install dependencies
  when: ansible_distribution_release != 'trusty'
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - openjdk-8-jre-headless
    - libjpeg-dev
    - libpng-dev
    - build-essential
    # lxml dependencies
    - libxml2-dev
    - libxslt1-dev
    # required by mr.developer
    - git
    # pdf generation dependencies
    - python-imaging
    - gif2png
    - cjk-latex
    - texlive-latex-extra
    - xsltproc
    - xvfb
    - xfonts-base
    - libreoffice
    - imagemagick
    - tralics
    - unzip
    - libxml2-utils
    - texlive-latex3
    - libedit-dev
    - zip
    - libreoffice-script-provider-python
    - ruby
    - inkscape
    - docbook-xsl-ns
    - openjdk-6-jre
    - texlive-fonts-recommended
    - memcached
    - librsvg2-bin
    - otf-stix
    - openjdk-7-jdk

# +++
# Install virtualenv
# +++

- stat:
    path: "{{ root_prefix }}/var/cnx/venvs"
  register: venvs_dir

- name: ensure the venvs directory exists
  become: yes
  when: not venvs_dir.stat.exists
  file:
    path: "{{ root_prefix }}/var/cnx/venvs"
    state: directory
    mode: 0755
    owner: www-data

- shell: which python2.4
  register: python24_path

# virtualenv 1.7.2 is the last known version to work with Python 2.4.
- name: download virtualenv 1.7.2 (for python 2.4)
  unarchive:
    src: https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.7.2.tar.gz#md5=b5d63b05373a4344ae099a68875aae78
    dest: .
    copy: no

- name: create the cnx-buildout virtualenv
  become: yes
  shell: "{{ python24_path.stdout }} virtualenv-1.7.2/virtualenv.py {{ root_prefix }}/var/cnx/venvs/cnx-buildout"

- name: delete virtualenv 1.7.2 source code
  file:
    path: virtualenv-1.7.2
    state: absent

# +++
# Install cnx-buildout
# +++

- name: copy cached python packages downloads directory
  become: yes
  copy:
    src: src/cnx-buildout/downloads
    dest: "{{ source_dir }}/cnx-buildout"
    owner: www-data

- name: run bootstrap
  become: yes
  become_user: www-data
  shell: "{{ root_prefix }}/var/cnx/venvs/cnx-buildout/bin/python bootstrap.py"
  args:
    chdir: "{{ source_dir }}/cnx-buildout"

- name: install simplejson 1.9.2
  become: yes
  pip:
    name: simplejson
    version: 1.9.2
    virtualenv: "{{ root_prefix }}/var/cnx/venvs/cnx-buildout"
    virtualenv_python: python2

- name: run buildout
  become: yes
  shell: ". {{ root_prefix }}/var/cnx/venvs/cnx-buildout/bin/activate && bin/buildout 2>&1 | tee buildout_output.txt"
  args:
    chdir: "{{ source_dir }}/cnx-buildout"

- name: install lxml 3.2.1
  become: yes
  shell: ". bin/libs.sh && {{ root_prefix }}/var/cnx/venvs/cnx-buildout/bin/pip install lxml==3.2.1"
  args:
    chdir: "{{ source_dir }}/cnx-buildout"

- name: assign permissions group
  become: yes
  file:
    path: "{{ root_prefix }}/var/lib/cnx/cnx-buildout"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: update source code
  become: yes
  become_user: www-data
  shell: "bin/develop up -f"
  args:
    chdir: "{{ source_dir }}/cnx-buildout"

- name: git submodules update
  become: yes
  become_user: www-data
  shell: "for f in {{ source_dir }}/cnx-buildout/src/*; do cd $f && git submodule update --recursive || echo; done"

- name: rerun buildout
  become: yes
  shell: ". {{ root_prefix }}/var/cnx/venvs/cnx-buildout/bin/activate && bin/buildout 2>&1 | tee -a buildout_output.txt"
  args:
    chdir: "{{ source_dir }}/cnx-buildout"

# +++
# Start server
# +++

- name: configure zeoserver and instance under supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/plone.conf
    dest: "{{ root_prefix }}/etc/supervisor/conf.d/plone.conf"
    mode: 0644

- name: restart supervisor
  become: yes
  service:
    name: supervisor
    state: restarted
    sleep: 5
