---
# Installs the postgresql plxslt extension.

# +++
# Prerequisites
# +++

- name: install build utilities
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libxml2-dev
    - libxslt-dev
    # pkg-config is required for plxslt builds
    - pkg-config

# +++
# Install
# +++

- name: install plxslt
  become: yes
  shell: "make && make install"
  args:
    chdir: "{{ source_dir }}/plxslt"
