---

# +++
# Install
# +++

- name: install nginx
  become: yes
  apt:
    name: nginx
    state: present

# +++
# Configure
# +++

- name: disable default site
  become: yes
  file:
    path: "{{ root_prefix }}/etc/nginx/sites-enabled/default"
    state: absent
  register: disabled_default_site

# BBB (1-Feb-2016) ubuntu 14.04
- name: make var/www available (on Ubuntu 14.04)
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"
  become: yes
  file:
    path: "{{ root_prefix }}/var/www"
    state: directory
    mode: 0755

# +++
# Init serivce
# +++

- name: start nginx
  become: yes
  service:
    name: nginx
    state: "{{ disabled_default_site.changed and 'reloaded' or 'started' }}"
