---
# Installs the postgresql session_exec extension.

# +++
# Prerequisites
# +++

- name: install build utilities
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential

# +++
# Install
# +++

- name: install session_exec
  become: "{{ ansible_os_family != 'Darwin' and 'yes' or 'no' }}"
  shell: "make USE_PGXS=1 PG_CONFIG={{ ansible_os_family == 'Darwin' and '/usr/local/opt/postgresql-{}/bin/pg_config'.format(postgres_version) or 'pg_config' }} && make USE_PGXS=1 PG_CONFIG={{ ansible_os_family == 'Darwin' and '/usr/local/opt/postgresql-{}/bin/pg_config'.format(postgres_version) or 'pg_config' }} install"
  args:
    chdir: "{{ source_dir }}/session_exec"
