---
# Unarchives the archived source packages on the host machine

- name: ensure source directory
  become: yes
  file:
    path: "{{ root_prefix }}/var/lib/cnx"
    state: directory
    owner: "{{ ansible_os_family == 'Darwin' and ansible_user_id or 'www-data' }}"

- name: plant the source archives
  become: yes
  unarchive:
    src: "{{ archives_dir }}/{{ item.name }}.tgz"
    dest: "{{ root_prefix }}/var/lib/cnx/"
    copy: yes
    owner: "{{ ansible_os_family == 'Darwin' and ansible_user_id or 'www-data' }}"
  with_items: "{{ source }}"
