---
root_prefix: ""

archive_db_name: repository
archive_db_user: rhaptos
archive_db_password: "roundtrip18239153]proselytizer"
archive_db_host: localhost
archive_db_port: 5432

# FIXME Not really yaml'ish to use space separated values...
# Note, don't confuse the usage of 'hosts' here with ansible 'hosts'.
# 'hosts' is a space separated value containing hostnames or ip addresses
# where a memcached instance is running.
memcached_hosts: localhost

varnish_port: 80

authoring_db_name: cnxauthoring
authoring_db_user: cnxauthoring
authoring_db_password: "solitarily64670059:imprecations"
authoring_db_host: localhost
authoring_db_port: 5432

zope_host: legacy.cnx.org
zope_port: 8888
archive_host: archive.cnx.mulich.com
archive_port: 6789
publishing_host: archive.cnx.mulich.com
publishing_port: 6543
authoring_host: authoring.cnx.mulich.com
authoring_port: 6420

zope_domain: legacy.cnx.org
arclishing_domain: archive.cnx.mulich.com
frontend_domain: cnx.mulich.com
accounts_domain: accounts.mulich.com

accounts_consumer_token: 
accounts_consumer_secret: 
accounts_disable_verify_ssl: no
