---
root_prefix: "{{ ansible_os_family == 'Darwin' and '/usr/local' or '' }}"

archive_db_name: cnxarchive
archive_db_user: cnxarchive
archive_db_password: cnxarchive
archive_db_host: localhost
archive_db_port: 5432

# FIXME Not really yaml'ish to use space separated values...
# Note, don't confuse the usage of 'hosts' here with ansible 'hosts'.
# 'hosts' is a space separated value containing hostnames or ip addresses
# where a memcached instance is running.
memcached_hosts: localhost

authoring_db_name: cnxauthoring
authoring_db_user: cnxauthoring
authoring_db_password: cnxauthoring
authoring_db_host: localhost
authoring_db_port: 5432

zope_host: zope.local.cnx.org
zope_port: 8888
archive_host: 0.0.0.0
archive_port: 6789
publishing_host: 0.0.0.0
publishing_port: 6543
authoring_host: 0.0.0.0
authoring_port: 8080

zope_domain: legacy.local.cnx.org
arclishing_domain: archive.local.cnx.org
frontend_domain: local.cnx.org
accounts_domain: accounts.local.openstax.org

accounts_consumer_token: 
accounts_consumer_secret: 
accounts_disable_verify_ssl: yes
