---
# Install Python 3.x

- name: add deadsnakes ppa
  become: yes
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'

- name: install python 3.6
  become: yes
  apt:
    name:
      - "python3.6-dev"
      - "python3.6-venv"
    state: present
